### ISSUE TITLE
Node and utf-8 do not agree

### ISSUE THREAD

**Issue by the42** [mechatroner/rainbow_csv#19]
When executing RBQL using the node backend, node complains aboout broken utf-8. The error ist:

```
IO handling
Unable to decode input table as UTF-8. Use binary (latin-1) encoding instead
```

When I set `let g:rbql_encoding = 'latin-1` I get the expected result.

Is this a buggy CSV-file I have (claims to be utf-8 at least) or is there a bug in the Neovim - Windows - node   -  Pipeline?

**Comment by mechatroner** [comment]
Well, I would prefer if it was a problem with the file, obviously. There are multiple ways to test this:
1. Try to run with utf-8 encoding and python backend
2. Try to run rbql command directly against it: `rbql-js --input /path/to/the/file.txt`
3. Check with iconv or another tool: https://stackoverflow.com/a/115262/2898283

**Comment by the42** [comment]
As I am by policy not allowed to install Python on this Windows 10 computer, I used the command line RBQL-tool and the output is:

```
buffer.js:608
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:608:37)
    at Buffer.toString (buffer.js:805:14)
    at CSVRecordIterator.process_data_bulk (C:\Users\HoechtlJ\AppData\Roaming\npm\node_modules\rbql\rbql_csv.js:375:41)
    at C:\Users\HoechtlJ\AppData\Roaming\npm\node_modules\rbql\rbql_csv.js:433:41
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  code: 'ERR_STRING_TOO_LONG'
}
```

If guess the whole file must fit into an utf8 string buffer and this is the problem (> 0x1fffffe8 characters) as the file is 561MB. I split the file in two parts and now the query succeeds.

Does the Python implementation also have this limitation? My files don't get much larger than this btw.

**Comment by the42** [comment]
Strangely if I open the same split CSV file in Neovim an execute the same command (changed the vim setting to use utf-8 RBQL encoding) I again get the error message 

```
IO handling
Unable to decode input table as UTF-8. Use binary (latin-1) encoding instead
```

Now I don't know what is going on.

**Comment by mechatroner** [comment]
Thanks @the42 , I had no idea about the size limit. In the hindsight, it makes sense that JavaScript would have it, I am not sure that there is an easy fix though, see the explanation below. It actually took me a while to figure out what is going on.
1. Explanation of why you see different errors.
This is because rbql is getting executed with different parameters: in Vim it doesn't have `bulk_read` flag set, while in node version we set the flag (although probably we shouldn't set it there, I need to think about it a little)
2. Now why do we need this `bulk_read` mode altogether? I introduced it because otherwise it is nearly impossible to catch encoding errors in JS, unlike Python it just silently swallows bad utf-8, and in case of a simple query like `select *` the output would not match the input without utf-8 validation. There is supposed to be a way to handle utf-8 streaming data in JS (`this.decoder = new util.TextDecoder(encoding, {fatal: true, stream: true});`), but it is completely broken in Electron, so we can't rely on it everywhere, that's why `bulk_read` flag is there, which is also appear to have a critical flaw that you just discovered. But I think it is actually fine to disable `bulk_read` by default in the cli version of rbql-js

**Comment by mechatroner** [comment]
I disabled the bulk mode in the cli version of node-js, so it should now handle huge files (because of the streaming mode). At least if you are not trying to sort them, in that case, due to the current sorting implementation, node js could still run out of memory. BTW there was a way to force streaming mode in the previous version too by passing the input through stdin. 
Regarding your original problem, I still think that the root cause was some encoding issues with the file, RBQL uses standard util.TextDecoder, so if it throws an exception while trying to parse a chunk of data there is nothing I can do.
