### ISSUE TITLE
Failed to load Python host.

### ISSUE THREAD

**Issue by mmtechslv** [mechatroner/rainbow_csv#27]
I installed `vim-rainbow_csv` using `vim-plug`. However, when I press F5 I get the following error:

`function provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4
Vim(if):Error invoking 'poll' on channel 8:^@ch 8 was closed by the client
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is av
ailable in messages.
Press ENTER or type command to continue`

I `did pip install rbql`, but it did not fix anything.
What could be the cause of this error?

**Comment by mechatroner** [comment]
My guess is that it could be something wrong with your neovim installation, I tried to google your error and found some [results](https://www.google.com/search?q=%22client+Failed+to+load+python+host%22). Do other python-based plugins work correctly in your editor? 
If nothing helps, you can set a special variable `let g:rbql_use_system_python=1` in your vim config. I just added this config option, so you would need to update rainbow_csv first in order to use it, see my last commit. After this Vim/Neovim will use system python interpreter instead of the built-in one. Please let me know if it doesn't work.
PS you don't have to pip install rbql, it is already built-in into rainbow_csv.

**Comment by mmtechslv** [comment]
Thank you for the quick response! Updating the plugin and setting the special variable helped. It works now without errors.  Thanks!
Note: I am not sure what plugins I use are based on python but I have not received any similar error. Here are the set of plugins that I currently use:
`
Plug 'preservim/NERDTree'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/syntastic'
Plug 'mechatroner/rainbow_csv'
Plug 'morhetz/gruvbox'
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install' }
Plug 'nvie/vim-flake8'
Plug 'vim-airline/vim-airline'
Plug 'hdima/python-syntax'
Plug 'majutsushi/tagbar'
Plug 'ervandew/supertab'
Plug 'wesq3/vim-windowswap'
Plug 'sirver/ultisnips'
Plug 'junegunn/fzf.vim'
Plug 'godlygeek/tabular'
Plug 'benmills/vimux'
Plug 'gilsondev/searchtasks.vim'
Plug 'honza/vim-snippets'
Plug 'sirver/ultisnips'
Plug 'vim-airline/vim-airline-themes'
Plug 'altercation/vim-colors-solarized'
Plug 'jpalardy/vim-slime'
Plug 'yuttie/comfortable-motion.vim'
Plug 'kkpmw/vim-sendtowindow'
Plug 'airblade/vim-gitgutter'
`

**Comment by mechatroner** [comment]
I am glad it worked, @mmtechslv !
