### ISSUE TITLE
Doesn't handle newlines inside quoted field

### ISSUE THREAD

**Issue by ju1ius** [mechatroner/rainbow_csv#3]
Hi,
When a quoted field contains newline characters, the plugin interprets them as a row delimiter:

![rainbow_csv](https://user-images.githubusercontent.com/218404/42461588-22ff8116-83a1-11e8-8d5f-70d946758ac8.png)

AFAICT, newlines inside quoted fields are allowed by the spec:
```ebnf
escaped = DQUOTE *(TEXTDATA / COMMA / CR / LF / 2DQUOTE) DQUOTE
```

**Comment by mechatroner** [comment]
Hi, @ju1ius !
Newlines inside double-quoted fields represent a fundamental problem, see my arguments here: mechatroner/vscode_rainbow_csv#4 You are welcome to join the discussion there.  
As I've mentioned in the VSCode ticket, there is an experimental branch of rainbow csv in vim which provide "correct" highlighting for newlines in double-quoted fields: https://github.com/mechatroner/rainbow_csv/tree/rfc_grammar

At some point I will include it in the master version as a special mode. 

But since this is a fundamental issue, Vim can't really solve it. Instead Vim just sort of "hides" the problem, and it doesn't always work, sometimes `:syntax sync fromstart` command have to be used.

**Comment by mechatroner** [comment]
Done. https://github.com/mechatroner/rainbow_csv#working-with-multiline-csv-fields provide some details. Maybe I will write a short text later to explain the exact meaning of "g:multiline_search_range" variable
