### ISSUE TITLE
Don't modify laststatus

### ISSUE THREAD

**Issue by igorlfs** [mechatroner/rainbow_csv#45]
Hello,

for some reason, the plugin sets laststatus to 2 every time a csv buffer is focused. Why is it like that? Could we have an option to disable that?

**Comment by mechatroner** [comment]
Hey, thanks for reporting!
Sorry for the late response, the plugin indeed sets `set laststatus=2`, I will look into this and try to find a workaround.

**Comment by igorlfs** [comment]
Oh, shoot!

I closed this issue because I just noticed I actually wanted to report it in the [other](https://github.com/cameron-wags/rainbow_csv.nvim) rainbow csv plugin (which I just did). If you wanna look into that here, that's cool too :)

**Comment by brdoney** [comment]
Just checking, is the `set laststatus=2` done to support the Select and Update status line features? Because if so, one option is to have that feature be disableable altogether.

Also maybe of note: I checked and those status line features do seem to work fine with `set laststatus=3` (which I'd imagine is the main alternative setting to 2, especially for Neovim users), although the status line can definitely be a little far from the window with the CSV buffer if there's a bunch of splits. So really, if the goal is to maintain the current functionality, `laststatus` could just be set if its value is not currently 3.

**Comment by mechatroner** [comment]
Thanks, @brdoney , you are right - `laststatus` modification is not needed for the core functionality. I removed it as well as `number` adjustment. The plugin should respect user configuration. Fixed.
